services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\GiftVoucherBundle\Controller\:
        resource: '../../Controller/*'
        bind:
            $roleNeeded: '%c975_l_gift_voucher.roleNeeded%'

    c975L\GiftVoucherBundle\Form\:
        resource: '../../Form/*'

    c975L\GiftVoucherBundle\Service\:
        resource: '../../Service/*'

    c975L\GiftVoucherBundle\Twig\:
        resource: '../../Twig/*'
