services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\GiftVoucherBundle\Controller\:
        resource: '../../Controller/*'

    c975L\GiftVoucherBundle\Form\:
        resource: '../../Form/*'

    c975L\GiftVoucherBundle\Service\:
        resource: '../../Service/*'

    c975L\GiftVoucherBundle\Twig\:
        resource: '../../Twig/*'