services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\GiftVoucherBundle\Service\:
        resource: '../../Service/*'

    c975L\GiftVoucherBundle\Twig\:
        resource: '../../Twig/*'